const customEntries = [
  `api.5rocks.io`,
  `52e901f500821d2b94000005.api.5rocks.io`,
  `action.adzcore.com`,
  `setting.adzcore.com`,
  `api.appsflyer.com`,
  `t.appsflyer.com`,
  `track.appsflyer.com`,
  `tap-nexus.appspot.com`,
  `live.chartboost.com`,
  `e.crashlytics.com`,
  `settings.crashlytics.com`,
  `graph.facebook.com`,
  `notification.fello.net`,
  `data.flurry.com`,
  `control.kochava.com`,
  `thanks.lobi.co`,
  `155376.measurementapi.com`,
  `ad-analytics-bootstrap.metaps.com`,
  `api-analytics-bootstrap.metaps.com`,
  `api-analytics.metaps.com`,
  `14642.engine.mobileapptracking.com`,
  `bam.nr-data.net`,
  `tr.pubnative.net`,
  `rayjump.com`,
  `res.rayjump.com`,
  `net.rayjump.com`,
  `setting.rayjump.com`,
  `us01.rayjump.com`,
  `api.smbeat.jp`,
  `control.smbeat.jp`,
  `trk-optimize.com`,
  `stats.unity3d.com`
];

module.exports = customEntries;